from callbacks.register_find_movie_callbacks import register_find_movie_callbacks
from callbacks.register_overview_callbacks import register_overview_callbacks
from callbacks.register_result_page_callbacks import register_result_page_callbacks